### PR TITLE
fix: Open command on linux

### LINKED ISSUE #207: Quickstart Step 5: `open` command in multistage-delivery.sh doesn't work on Linux
https://github.com/keptn/examples/blob/0f8c0532c8e84f67fdc245ab0e8fef5362c15f43/quickstart/multistage-delivery.sh#L200
`multistage-delivery.sh` throws `couldn't find a file descriptor referring to the console`  error here ^ when I run this script on my Ubuntu 16.04 LTS machine. 

https://github.com/keptn/examples/blob/0f8c0532c8e84f67fdc245ab0e8fef5362c15f43/quickstart/expose-keptn.sh#L124
Same error occurs here ^ as well

This is because `open` on Linux refers to some other command
```
$ man open
NAME
       openvt - start a program on a new virtual terminal (VT).
...
```
The equivalent command on Linux is `xdg-open` ([SO thread on this issue](https://stackoverflow.com/questions/42463929/couldnt-find-a-file-descriptor-referring-to-the-console-on-ubuntu-bash-on-win))
```
$ man xdg-open
NAME
       xdg-open - opens a file or URL in the user's preferred application
...
```

## Definition of done
- [ ] Define `open` command as a bash variable (e.g., `$OPEN`) and set it [based on the operating system](https://stackoverflow.com/questions/394230/how-to-detect-the-os-from-a-bash-script/18434831) (we do something similar in our [keptn-on-k3s install script](https://github.com/keptn-sandbox/keptn-on-k3s/blob/4242fae960490f54756457d0e4e96cc0e72b469d/install-keptn-on-k3s.sh#L150)) and evaluate this bash variable instead of `open` directly in multistage-delivery.sh
- [ ] Do the same for expose-keptn.sh

### PR DESCRIPTION
**Pull request by TannerGabriel**
## This PR

Currently, the open command used in the quickstart tutorial scripts does not work on Linux machines, as described in issue #207. Now we check which OS the script is being executed on and change the command accordingly.

### Related Issues

Fixes #207

### CODE REVIEW

File: quickstart/expose-keptn.sh [hunk 1]
```diff
@@ -121,13 +121,20 @@ do
   # echo "retries:  $retries / $MAX_RETRIES" 
   if [ ${http_code} -eq 200 ]; then
     echo "Attempting to open Keptn bridge on http://$INGRESS_IP.nip.io:$INGRESS_PORT/bridge"
-    if ! command -v open &> /dev/null
+
+     if [[ "$OSTYPE" == "linux-gnu"* ]]; then
+      OPEN=('xdg-open')
+    else
+        OPEN=('open')
```
Comment (mowies) [inline quickstart/expose-keptn.sh:128]: Indentation is a little off here :)

File: quickstart/multistage-delivery.sh [hunk 2]
```diff
@@ -199,11 +199,17 @@ echo "Attempt to open Keptn Bridge in 5 seconds..."
...
+else
+    OPEN=('open')
+fi
+
+if ! command -v "${OPEN[@]}" &> /dev/null
 then
   echo http://$INGRESS_IP.nip.io:$INGRESS_PORT/bridge/project/podtatohead/sequence
 else
-  open http://$INGRESS_IP.nip.io:$INGRESS_PORT/bridge/project/podtatohead/sequence
+  "${OPEN[@]}" http://$INGRESS_IP.nip.io:$INGRESS_PORT/bridge/project/podtatohead/sequence
```
Comment (mowies) [inline quickstart/multistage-delivery.sh:212]: Indentation is different between the two if blocks again :)

File: quickstart/expose-keptn.sh (hunk 1 above)
Comment (TannerGabriel) [reply quickstart/expose-keptn.sh:128]: That is odd because my editor displays them the same. I will automatically format the document, which should work.

**Review by mowies — APPROVED** [review]
